apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: voletech

parameters:
  - name: VAULT_HOME
    required: true
    value: "/deployments/vault"
    description: "Vault home directory"
    
  - name: KEYSTORE_PASSWORD
    required: true
    value: "MASK-5dOaAVafCSd"
    description: "Vault Keystore password"
    
  - name: KEYSTORE_ALIAS
    required: true
    value: "vault"
    description: "Vault Keystore alias"
    
  - name: SALT
    required: true
    value: "1234abcd"
    description: "Vault Keystore salt"
    
  - name: ITERATION_COUNT
    required: true
    value: "120"
    description: "Vault Keystore iteration count"
    
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: voletech
    name: voletech
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: voletech:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/benemon/voletech
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: jboss-eap70-openshift:1.4
          namespace: openshift
      type: Source
    triggers:
    - generic:
        secret: d2c09fa66efd9676
      type: Generic
    - github:
        secret: dc76af78a6e644a2
      type: GitHub
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
  status: {}
  
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 12
    labels:
      app: voletech
    name: voletech
  spec:
    replicas: 1
    selector:
      deploymentconfig: voletech
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: voletech
          deploymentconfig: voletech
      spec:
        containers:
        - env:
          - name: VAULT_HOME
            value: ${VAULT_HOME}
          - name: KEYSTORE_PASSWORD
            value: ${KEYSTORE_PASSWORD}
          - name: KEYSTORE_ALIAS
            value: ${KEYSTORE_ALIAS}
          - name: SALT
            value: ${SALT}
          - name: ITERATION_COUNT
            value: ${ITERATION_COUNT}
          image: voletech:latest
          imagePullPolicy: Always
          name: voletech
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /deployments/vault
            name: vault
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: vault
          secret:
            secretName: vault
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - voletech
        from:
          kind: ImageStreamTag
          name: voletech:latest
      type: ImageChange
    - type: ConfigChange
  status: {}
    
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 1
    labels:
      app: voletech
    name: voletech
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: voletech:latest
      generation: null
      importPolicy: {}
      name: latest
  status: {}
  
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: voletech
    name: voletech
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    selector:
      deploymentconfig: voletech
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
    
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: voletech
    name: voletech
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: voletech
      weight: 100
  status: {}
  
- apiVersion: v1
  data:
    VAULT.dat: rO0ABXNyAC1vcmcucGlja2V0Ym94LnBsdWdpbnMudmF1bHQuU2VjdXJpdHlWYXVsdERhdGEAAAAAAAAAAQMAAHhwc3IAEWphdmEubGFuZy5JbnRlZ2VyEuKgpPeBhzgCAAFJAAV2YWx1ZXhyABBqYXZhLmxhbmcuTnVtYmVyhqyVHQuU4IsCAAB4cAAAAAFzcgAmamF2YS51dGlsLmNvbmN1cnJlbnQuQ29uY3VycmVudEhhc2hNYXBkmd4SnYcpPQMAA0kAC3NlZ21lbnRNYXNrSQAMc2VnbWVudFNoaWZ0WwAIc2VnbWVudHN0ADFbTGphdmEvdXRpbC9jb25jdXJyZW50L0NvbmN1cnJlbnRIYXNoTWFwJFNlZ21lbnQ7eHAAAAAPAAAAHHVyADFbTGphdmEudXRpbC5jb25jdXJyZW50LkNvbmN1cnJlbnRIYXNoTWFwJFNlZ21lbnQ7Unc/QTKbOXQCAAB4cAAAABBzcgAuamF2YS51dGlsLmNvbmN1cnJlbnQuQ29uY3VycmVudEhhc2hNYXAkU2VnbWVudB82TJBYkyk9AgABRgAKbG9hZEZhY3RvcnhyAChqYXZhLnV0aWwuY29uY3VycmVudC5sb2Nrcy5SZWVudHJhbnRMb2NrZlWoLCzIausCAAFMAARzeW5jdAAvTGphdmEvdXRpbC9jb25jdXJyZW50L2xvY2tzL1JlZW50cmFudExvY2skU3luYzt4cHNyADRqYXZhLnV0aWwuY29uY3VycmVudC5sb2Nrcy5SZWVudHJhbnRMb2NrJE5vbmZhaXJTeW5jZYgy51N7vwsCAAB4cgAtamF2YS51dGlsLmNvbmN1cnJlbnQubG9ja3MuUmVlbnRyYW50TG9jayRTeW5juB6ilKpEWnwCAAB4cgA1amF2YS51dGlsLmNvbmN1cnJlbnQubG9ja3MuQWJzdHJhY3RRdWV1ZWRTeW5jaHJvbml6ZXJmVahDdT9S4wIAAUkABXN0YXRleHIANmphdmEudXRpbC5jb25jdXJyZW50LmxvY2tzLkFic3RyYWN0T3duYWJsZVN5bmNocm9uaXplcjPfr7mtbW+pAgAAeHAAAAAAP0AAAHNxAH4ACnNxAH4ADgAAAAA/QAAAc3EAfgAKc3EAfgAOAAAAAD9AAABzcQB+AApzcQB+AA4AAAAAP0AAAHNxAH4ACnNxAH4ADgAAAAA/QAAAc3EAfgAKc3EAfgAOAAAAAD9AAABzcQB+AApzcQB+AA4AAAAAP0AAAHNxAH4ACnNxAH4ADgAAAAA/QAAAc3EAfgAKc3EAfgAOAAAAAD9AAABzcQB+AApzcQB+AA4AAAAAP0AAAHNxAH4ACnNxAH4ADgAAAAA/QAAAc3EAfgAKc3EAfgAOAAAAAD9AAABzcQB+AApzcQB+AA4AAAAAP0AAAHNxAH4ACnNxAH4ADgAAAAA/QAAAc3EAfgAKc3EAfgAOAAAAAD9AAABzcQB+AApzcQB+AA4AAAAAP0AAAHQADHZiOjpwYXNzd29yZHVyAAJbQqzzF/gGCFTgAgAAeHAAAAAQsif8zvrEXMNy3WElycn9NHBweHg=
    vault.keystore: zs7OzgAAAAIAAAABAAAAAwAFdmF1bHQAAAFbNJYdj6ztAAVzcgAzY29tLnN1bi5jcnlwdG8ucHJvdmlkZXIuU2VhbGVkT2JqZWN0Rm9yS2V5UHJvdGVjdG9yzVfKWecwu1MCAAB4cgAZamF2YXguY3J5cHRvLlNlYWxlZE9iamVjdD42PabDt1RwAgAEWwANZW5jb2RlZFBhcmFtc3QAAltCWwAQZW5jcnlwdGVkQ29udGVudHEAfgACTAAJcGFyYW1zQWxndAASTGphdmEvbGFuZy9TdHJpbmc7TAAHc2VhbEFsZ3EAfgADeHB1cgACW0Ks8xf4BghU4AIAAHhwAAAADzANBAgNT13spcNDnwIBFHVxAH4ABQAAAJD21jg8EyypwlEwDwiiOLfI4mJfO2Is93n2UWLOmxoGVmiXjVHyxZxNY6afAoxalG10jEtegl6csvt3CtBUpLMCaqQJ65FpVMhZVxsKFi9lbeXY83WZGqlgGRylK5keGFMQ2jFTevZIQvS1tMICwgHFFWIEmd8/11bKJB/WQaQWUJvNnyshyaBL5kw7a+luI4d0ABZQQkVXaXRoTUQ1QW5kVHJpcGxlREVTdAAWUEJFV2l0aE1ENUFuZFRyaXBsZURFUz8zZ6SM4/qOCYcBtuOrvmKDG887
  kind: Secret
  metadata:
    creationTimestamp: null
    name: vault
  type: Opaque
